---
deployment:
  tasks:
    # 1. Install semua dependency dari package.json
    - npm install

    # 2. Build proyek. Vite akan membuat folder "dist"
    - npm run build

    # 3. Hapus isi folder tujuan untuk memastikan kebersihan
    - rm -rf /home1/elternit/public_html/fly/dist/*

    # 4. Salin semua file dari hasil build (dist) ke folder tujuan
    #    Perhatikan tanda titik (.) di akhir dist/. untuk menyalin semua, termasuk file tersembunyi
    - cp -R dist/. /home1/elternit/public_html/fly/dist/

    # 5. Salin .htaccess secara eksplisit ke folder tujuan
    - cp public/.htaccess /home1/elternit/public_html/fly/dist/

    # 6. Atur izin (permission) untuk semua direktori
    - find /home1/elternit/public_html/fly/dist/ -type d -exec chmod 755 {} \;

    # 7. Atur izin (permission) untuk semua file
    - find /home1/elternit/public_html/fly/dist/ -type f -exec chmod 644 {} \;