---
deployment:
  tasks:
    # 1. Install all dependencies from package.json
    - npm install

    # 2. Build the project. Vite will create a "dist" folder
    - npm run build

    # IMPORTANT: The following tasks copy the built files to public_html/fly/
    # For this to work, the domain's "Document Root" in cPanel MUST be set to "public_html/fly".

    # 3. Copy all files from the build output (dist) to the target folder
    # Note the dot (.) at the end of dist/. to copy everything, including hidden files
    - cp -R dist/. /home1/elternit/public_html/fly/

    # 4. Explicitly copy .htaccess to the target folder
    - cp public/.htaccess /home1/elternit/public_html/fly/

    # 5. Set permissions for all directories
    - find /home1/elternit/public_html/fly/ -type d -exec chmod 755 {} \;

    # 6. Set permissions for all files
    - find /home1/elternit/public_html/fly/ -type f -exec chmod 644 {} \;